ktor:
  application:
    modules:
      - com.m3sy.ktor.explorer.cultural.ApplicationKt.module
  deployment:
    port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cultural-explorer
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your-256-bit-secret-which-is-very-secure
  issuer: demo-app
  expiration-ms: 900000           # 15 minutes
  refresh-expiration-ms: 2592000000  # 30 days

logging:
  level:
    root: INFO
    com.m3sy.ktor.explorer.cultural: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    enabled: true